- name: Install OpenJDK on managed node
  hosts: managed
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
